#create a servece of mysql

version: "2.4"
services: 
  db: 
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    environment: 
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
  app:
    build: ./weight
    depends_on:
      - db
