#!/bin/bash

BRANCH=$1
SHA=$2
PORTXT=$3
FLAG=$4

echo -e "\e[1;31m\t Trying to building up service\e[0m"

echo "$BRANCH"
echo "$SHA"
echo "$PORT"
echo "$FLAG"

if [ "$BRANCH" = "billing" ] || [ "$BRANCH" = "weight" ] || [ "$BRANCH" = "master" ]
    then
        rm -rf "/home/ec2-user/tmp/build_$BRANCH/"
        echo -e "\e[1;31m\t Start Building up service\e[0m"

        echo -e "\e[1;36m[+] Setting up Job Control\e[0m"        
        set -m && \

        echo -e "\e[1;36m[+] Making Temp dir for branch\e[0m" && \
        mkdir -p "/home/ec2-user/tmp/build_$BRANCH" && \

        echo -e "\e[1;36m[+] Moving into tmp folder\e[0m" && \
        cd "/home/ec2-user/tmp/build_$BRANCH" && \

        echo -e "\e[1;36m[+] Cloning last version of the project from git\e[0m" && \
        git clone "https://github.com/SSilvering/Gan-Shmuel.git" && \

        echo -e "\e[1;36m[+] Moving into $BRANCH folder\e[0m" && \
        cd "/home/ec2-user/tmp/build_$BRANCH/Gan-Shmuel/$BRANCH" && \

        echo -e "\e[1;36m[+] Chechout for $BRANCH branch\e[0m" && \
        git checkout "$BRANCH" "--" && \

        echo -e "\e[1;36m[+] Building up $BRANCH service\e[0m" && \

        export TAG="$SHA" && \
        export PORT="$PORTXT" && \

        if [ "${FLAG}" = 'commit' ]
        then
            TMP=$(docker image ls | grep -c "${SHA}")

            if [ "$TMP" -eq 1 ] 
            then
                docker-compose up -d --force-recreate
                echo "OLD IMAGE"
            else
                docker-compose up -d --build --force-recreate 
                echo "NEW IMAGE"
            fi  
        
        elif [ "${FLAG}" = 'test' ]
        then  # ADD PORT
            TMP=$(docker image ls | grep -c "${SHA}")

            if  [ "$TMP" -eq 1 ]
            then
                export PORT="$PORTXT" && \
                docker-compose up -d --force-recreate && \
                CHECK=$(/home/ec2-user/tmp/build_${BRANCH}/Gan-Shmuel/${BRANCH}/app/tests/main_test.sh)

                if [ "$CHECK" ]
                then
                    echo "OK"

                fi

                echo "IMAGE EXIST"
            else
                export PORT="$PORTXT" && \
                docker-compose up -d --force-recreate && \
                CHECK=$(/home/ec2-user/tmp/build_${BRANCH}/Gan-Shmuel/${BRANCH}/app/tests/main_test.sh) && \

                if [ "$CHECK" ]
                then
                    echo "OK"

                fi
                echo "IMAGE NOT EXIST"
            fi

            echo "test: test"
        
        elif [ "${FLAG}" = 'master' ]
        then
            # docker-compose run -p db && \
            # docker-compose run -p "$PORT":5000 app
            echo "test: merge"
        fi

        
        echo -e "\e[1;36m[+] Removing folder\e[0m" && \
        rm -rf "/home/ec2-user/tmp/build_$BRANCH/" && \

        echo -e "\e[1;36m[+] Exiting chroot\e[0m" && \
        exit
    else
        echo -e "Problem with executing script\n"
    fi    