version: '3.8'

services: 
  ci-service:
      build: .
      ports: 
          - 80:5000
      environment: 
          PORT: 5000
          FLASK_DEBUG: 1
          GIT_PYTHON_REFRESH: quiet