version: '3.8'

services: 
  ci-service:
      build: .
      privileged: true
      network_mode: host
      pid: "host"
      ipc: host
      volumes:
          - /:/host
            #      ports: 
            #          - 80:5000
      environment: 
          PORT: 80
          FLASK_DEBUG: 1
          GIT_PYTHON_REFRESH: quiet
