version: "2.1"
services: 
  db: 
    image: mysql
    container_name: mysql_weight
    command: "--default-authentication-plugin=mysql_native_password"
    environment: 
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
        interval: 12s
        timeout: 180s
        retries: 120
    
  app:
    image: "weight:${TAG}" 
    build: ./weight
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "$PORT:8080"
